/* effect.c
 */

#include "table/effect.h"

const char * const k_effect_name[NUM_EFFECTS] = {
	/*           123456789-123456 */
	/*   0 */   "Bolt"
	/*   1 */ , "Bolt Spike"
	/*   2 */ , "Bolt Burst"
	/*   3 */ , "Flare"
	/*   4 */ , "Flare Burn"
	/*   5 */ , "Flare Burst"
	/*   6 */ , "Aqua"
	/*   7 */ , "Aqua Bash"
	/*   8 */ , "Aqua Burst"
	/*   9 */ , "Wind"
	/*  10 */ , "Wind Storm"
	/*  11 */ , "Wind Burst"

	/*  12 */ , "Vampire"
	/*  13 */ , "Vampire +"
	/*  14 */ , "Vampire + +"
	/*  15 */ , "Heal"
	/*  16 */ , "Heal+"
	/*  17 */ , "Heal+ +"
	/*  18 */ , "Repair"
	/*  19 */ , "Repair+"
	/*  20 */ , "Repair+ +"
	/*  21 */ , "Costdown"
	/*  22 */ , "Costdown+"
	/*  23 */ , "Costdown+ +"
	/*  24 */ , "Luck"
	/*  25 */ , "Luck+"
	/*  26 */ , "Luck+ +"

	/*  27 */ , "Knock Back"
	/*  28 */ , "TEC Up"
	/*  29 */ , "Thrust Down"
	/*  30 */ , "Piercing"
	/*  31 */ , "Quick Hit"
	/*  32 */ , "Parry"
	/*  33 */ , "Critical"
	/*  34 */ , "Desperation ATK"
	/*  35 */ , "Desperation DEF"
	/*  36 */ , "Paralyse Attack"
	/*  37 */ , "Sleep Attack"
	/*  38 */ , "Poison Attack"
	/*  39 */ , "Rust Attack"
};

const char * const k_effect_desc[NUM_EFFECTS] = {
	/*           123456789-123456789-123456789-123456 */
	/*   0 */   "Weak lightning element attack"
	/*   1 */ , "Medium lightning element attack"
	/*   2 */ , "Strong lightning element attack"
	/*   3 */ , "Weak fire element attack"
	/*   4 */ , "Medium fire element attack"
	/*   5 */ , "Strong fire element attack"
	/*   6 */ , "Weak water element attack"
	/*   7 */ , "Medium water element attack"
	/*   8 */ , "Strong water element attack"
	/*   9 */ , "Weak wind element attack"
	/*  10 */ , "Medium wind element attack"
	/*  11 */ , "Strong wind element attack"

	/*  12 */ , "Small chance of absorbing little HP"
	/*  13 */ , "Small chance of absorbing some HP"
	/*  14 */ , "Small chance of absorbing lots of HP"
	/*  15 */ , "Recover ~1 HP every ~4 seconds"
	/*  16 */ , "Recover ~5 HP every ~4 seconds"
	/*  17 */ , "Recover ~1~0 HP every ~4 seconds"
	/*  18 */ , "Recover ~1 DUR every  ~8 seconds"
	/*  19 */ , "Recover ~1 DUR every  ~4 seconds"
	/*  20 */ , "Recover ~1 DUR every  ~2 seconds"
	/*  21 */ , "Small reduction for special skills"
	/*  22 */ , "Medium reduction for special skills"
	/*  23 */ , "Large reduction for special skills"
	/*  24 */ , "+ ~5%% chance for enemy item drops"
	/*  25 */ , "+ ~1~0%% chance for enemy item drops"
	/*  26 */ , "+ ~1~5%% chance for enemy item drops"

	/*  27 */ , "Attacks knock the enemies back"
	/*  28 */ , "TEC increases a bit faster"
	/*  29 */ , "In mid-air, Down+ A to attack below"
	/*  30 */ , "Can hit multiple enemies"
	/*  31 */ , "Attack speed is slightly increased"
	/*  32 */ , "Higher chance of parrying"
	/*  33 */ , "Higher critical attack rate"
	/*  34 */ , "In a critical state, increases ATK"
	/*  35 */ , "In a critical state, increases DEF"
	/*  36 */ , "Adds a chance to cause paralysis"
	/*  37 */ , "Adds a chance to cause sleep"
	/*  38 */ , "Adds a chance to cause poison"
	/*  39 */ , "Adds a chance to cause rust"
};
